# Generated by Django 4.2.27 on 2025-12-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_enrollment_id_alter_userlessonprogress_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
