# Generated by Django 4.2.27 on 2025-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт до завершения'),
        ),
    ]
