# Generated by Django 4.2.27 on 2026-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonblock_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демо-урок (доступен всем)'),
        ),
    ]
